# https://github.com/jesseduffield/lazygit/blob/master/docs/Config.md

# From https://github.com/folke/tokyonight.nvim/blob/main/extras/lazygit/tokyonight_storm.conf
gui:
  scrollHeight: 8
  sidePanelWidth: 0.25
  expandFocusedSidePanel: true
  theme:
    activeBorderColor:
      - "#ff9e64"
      - "bold"
    inactiveBorderColor:
      - "#29a4bd"
    searchingActiveBorderColor:
      - "#ff9e64"
      - "bold"
    optionsTextColor:
      - "#7aa2f7"
    selectedLineBgColor:
      - "#2e3c64"
    cherryPickedCommitFgColor:
      - "#7aa2f7"
    cherryPickedCommitBgColor:
      - "#bb9af7"
    markedBaseCommitFgColor:
      - "#7aa2f7"
    markedBaseCommitBgColor:
      - "#e0af68"
    unstagedChangesColor:
      - "#db4b4b"
    defaultFgColor:
      - "#c0caf5"
  nerdFontsVersion: "3"

git:
  paging:
    colorArg: always
    pager: diff-so-fancy
