-- INFO: this two defaults are same as in vscode
--
-- local default_format_options = {
-- 	insertSpaceAfterCommaDelimiter = true,
-- 	insertSpaceAfterConstructor = false,
-- 	insertSpaceAfterSemicolonInForStatements = true,
-- 	insertSpaceBeforeAndAfterBinaryOperators = true,
-- 	insertSpaceAfterKeywordsInControlFlowStatements = true,
-- 	insertSpaceAfterFunctionKeywordForAnonymousFunctions = true,
-- 	insertSpaceBeforeFunctionParenthesis = false,
-- 	insertSpaceAfterOpeningAndBeforeClosingNonemptyParenthesis = false,
-- 	insertSpaceAfterOpeningAndBeforeClosingNonemptyBrackets = false,
-- 	insertSpaceAfterOpeningAndBeforeClosingNonemptyBraces = true,
-- 	insertSpaceAfterOpeningAndBeforeClosingEmptyBraces = true,
-- 	insertSpaceAfterOpeningAndBeforeClosingTemplateStringBraces = false,
-- 	insertSpaceAfterOpeningAndBeforeClosingJsxExpressionBraces = false,
-- 	insertSpaceAfterTypeAssertion = false,
-- 	placeOpenBraceOnNewLineForFunctions = false,
-- 	placeOpenBraceOnNewLineForControlBlocks = false,
-- 	semicolons = "ignore",
-- 	indentSwitchCase = true,
-- }
--
-- local default_preferences = {
-- 	quotePreference = "auto",
-- 	importModuleSpecifierEnding = "auto",
-- 	jsxAttributeCompletionStyle = "auto",
-- 	allowTextChangesInNewFiles = true,
-- 	providePrefixAndSuffixTextForRename = true,
-- 	allowRenameOfImportPath = true,
-- 	includeAutomaticOptionalChainCompletions = true,
-- 	provideRefactorNotApplicableReason = true,
-- 	generateReturnInDocTemplate = true,
-- 	includeCompletionsForImportStatements = true,
-- 	includeCompletionsWithSnippetText = true,
-- 	includeCompletionsWithClassMemberSnippets = true,
-- 	includeCompletionsWithObjectLiteralMethodSnippets = true,
-- 	useLabelDetailsInCompletionEntries = true,
-- 	allowIncompleteCompletions = true,
-- 	displayPartsForJSDoc = true,
-- 	disableLineTextInReferences = true,
-- 	includeInlayParameterNameHints = "none",
-- 	includeInlayParameterNameHintsWhenArgumentMatchesName = false,
-- 	includeInlayFunctionParameterTypeHints = false,
-- 	includeInlayVariableTypeHints = false,
-- 	includeInlayVariableTypeHintsWhenTypeMatchesName = false,
-- 	includeInlayPropertyDeclarationTypeHints = false,
-- 	includeInlayFunctionLikeReturnTypeHints = false,
-- 	includeInlayEnumMemberValueHints = false,
-- }

return {
  -- "pmizio/typescript-tools.nvim", -- Breaks telescope workspace symbols!!!!
  -- dependencies = { "nvim-lua/plenary.nvim", "neovim/nvim-lspconfig" },
  -- opts = {
  -- 	expose_as_code_action = "all",
  -- 	tsserver_file_preferences = { -- https://github.com/microsoft/TypeScript/blob/v5.0.4/src/server/protocol.ts#L3439
  -- 		includeInlayParameterNameHints = "all",
  -- 	},
  -- 	-- tsserver_format_options = { -- https://github.com/microsoft/TypeScript/blob/v5.0.4/src/server/protocol.ts#L3418
  -- 	-- },
  -- },
  -- ft = { "typescript", "javascript" },
}
